### ISSUE TITLE
fix `rm -rf /`

### ISSUE THREAD

**Issue by bpowers** [plasma-umass/browsix#29]
It currently fails with `ENOENT`, but it should actually leave the shell unusable.

**Comment by b1101** [comment]
There is an issue with '-r' flag: https://github.com/plasma-umass/browsix/blob/master/src/bin/rm.ts#L22
`!stats.isFile()` is incorrectly evaluated.
See console output of executing `rm -r boot` on both local and hosted versions: 
![result](https://cloud.githubusercontent.com/assets/12877905/14767054/0a71328e-0a1d-11e6-80e2-1adcc4c65b68.png)

**Comment by b1101** [comment]
The problem seems to be with the '-r' flag, especially on lines[14-33](https://github.com/plasma-umass/browsix/blob/master/src/bin/rm.ts#L14-33).
Statement on [line 33](https://github.com/plasma-umass/browsix/blob/master/src/bin/rm.ts#L33) is executed asynchronously(as a consequence, the directory may be not empty yet at the moment it is trying to be deleted)
Also fs.stat on [line 17](https://github.com/plasma-umass/browsix/blob/master/src/bin/rm.ts#L17) should take 'filename' as arg instead of 'dir'(otherwise the following logic fails)

Note that function, which the '-r' flag logic was 'adopted' from uses Sync variations of functions and so the results can differ.

**Comment by bpowers** [comment]
fixed by #30 + my small hack on top of that.  I'll open a separate issue for the .deletedFiles.log thing.  Thanks @b1101 !
